// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_array = require("rescript/lib/js/caml_array.js");
var Belt_Option = require("rescript/lib/js/belt_Option.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function matchCherryPickCommand(text) {
  var re = /^(?:\/cherrypick|\/cherry-pick)\s+(.+)$/gm;
  var branches = {};
  var $$break = false;
  while(!$$break) {
    var r = re.exec(text);
    if (r !== null) {
      var branch = Caml_array.get(r, 1);
      if (!(branch == null)) {
        branches[branch.trim()] = undefined;
      }
      
    } else {
      $$break = true;
    }
  };
  return Object.keys(branches);
}

function matchLabel(labelPrefixes, label) {
  return Belt_Option.map(Caml_option.undefined_to_opt(labelPrefixes.find(function (param) {
                      return label.startsWith(param);
                    })), (function (matched) {
                return label.substring(matched.length);
              }));
}

exports.matchCherryPickCommand = matchCherryPickCommand;
exports.matchLabel = matchLabel;
/* No side effect */
